### ISSUE TITLE
ZeroTier One not available on your system error message in Hass.io

### ISSUE THREAD

**Issue by sunflowerABB** [TomCzHen/hassio-addon-zerotier-one#2]
V 1.01 of ZeroTier One claims error message "Addon not available on your system" in Hass.io (HassOS 1.12 / Supervisor v140). Could you please update the add-on to fix this error?

**Comment by TomCzHen** [comment]
Upgraded 1.1.0 version.

I tested at  HassOS 2.10 on Raspberry Pi 3B+.
